import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import WalletContextProvider from "@/components/walletProvider";
import { Toaster } from 'sonner'
import { Buffer } from 'buffer';
global.Buffer = Buffer;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletContextProvider>
          <ViewTransitions>
            {children}
            <Toaster richColors position="bottom-center"/>
          </ViewTransitions>
        </WalletContextProvider>
      </body>
    </html>
  );
}